import React from 'react';
import { Link } from 'react-router-dom';

const Creators = () => {
  return (
    <div className="p-8  md:p-12 font-mulish   text-gray-800">
        <div className='max-w-2xl mx-auto'>
      <div className="   mx-auto text-center mb-12">
        <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-10">Welcome to PageFM : A World Built for Creators, by Creators</h1>
        <p className="text-lg md:text-xl leading-relaxed max-w-3xl mx-auto">
          Imagine a platform where your creativity isn’t just appreciated—it’s empowered, celebrated, and shared. At PageFM, we’ve created a space that goes beyond just readers and listeners; it’s a home for writers, voiceover artists, poets, songwriters, and creators of all kinds. A place where your talent can shine, connect with audiences, and reward you for your hard work.
        </p>
      </div>

      <div className="  mx-auto space-y-10 text-center">
        <p className="text-lg md:text-xl leading-relaxed">
          Whether you're a seasoned writer or just starting out, PageFM allows you to upload your Hindi or English content for readers to discover. Voiceover artists can bring your stories to life, creating a deep, emotional connection with listeners. Imagine someone narrating your poem or novel, breathing life into your words, and engaging audiences like never before.
        </p>
        <p className="text-lg md:text-xl leading-relaxed">
          Voiceover artists, you have the freedom to choose content that resonates with you, record it, and share it with a community eager to listen. Become the voice behind the story, the reason someone stays captivated till the last word.
        </p>
      </div>

      <div className="  mx-auto text-center mt-20 mb-12">
        <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">A Platform That Truly Supports Creators</h2>
        <p className="text-lg md:text-xl leading-relaxed">
          At PageFM, we believe that creators deserve more. We share 50% of the income generated by your content. Whether you're a writer or a voiceover artist, we make sure your contribution is rewarded fairly. We want to create a platform that is as loyal to you as you are to your craft.
        </p>
        <p className="text-lg md:text-xl leading-relaxed">
          For example, if a creator’s story is loved and a voiceover artist chooses to narrate it, both parties share in the success. When your work shines, we make sure the light is shared equally.
        </p>
      </div>

      <div className="  mx-auto space-y-8 mt-20 text-center">
        <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">A Creative Collaboration Like No Other</h2>
        <p className="text-lg md:text-xl leading-relaxed">
          This isn’t just a website; it’s a community where creators help creators. If you’re a writer who needs support to reach a wider audience, we’ve got you covered. Voiceover artists looking to collaborate on engaging projects can find their stage here.
        </p>
        <p className="text-lg md:text-xl leading-relaxed">
          Need help with background music for your poetry or song? We’re here to assist. Songwriters, poets, and ghazal writers have a dedicated space to record and showcase their musical creations.
        </p>
      </div>

      <div className="  mx-auto text-center my-12 mt-20">
        <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Why Choose PageFM?</h2>
        <ul className="list-disc list-inside text-left text-lg md:text-xl max-w-2xl mx-auto space-y-4">
          <li>50% Revenue Sharing: We offer one of the most generous creator revenue models out there.</li>
          <li>Creative Freedom: Voiceover artists can narrate any book they feel connected to, creating a unique bond with listeners.</li>
          <li>Collaborative Growth: Writers, voiceover artists, musicians—all working together to help each other succeed.</li>
          <li>Support for Songwriters & Poets: A dedicated space to record and earn from your musical creations.</li>
        </ul>
        <p className="text-lg md:text-xl leading-relaxed mt-6 max-w-2xl mx-auto">
          We are more than just a platform—we are here to support you at every step. Whether you need help with recording, creating engagement, or building a following, PageFM is your partner in growth.
        </p>
      </div>

      <div className="  mx-auto text-center my-20 mt-20">
        <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">Examples of Why You Should Join:</h2>
        <div className="space-y-6">
          <div className="bg-white p-6 rounded-md shadow-lg border-l-4 border-yellow-500 text-left">
            <h3 className="text-2xl font-semibold text-yellow-600">For Writers</h3>
            <p className="text-lg mt-2">Imagine your short story being turned into an engaging audiobook, narrated by a talented voiceover artist and shared across our platform. You both share the earnings, while listeners immerse themselves in your world.</p>
          </div>
          <div className="bg-white p-6 rounded-md shadow-lg border-l-4 border-green-500 text-left">
            <h3 className="text-2xl font-semibold text-green-600">For Voiceover Artists</h3>
            <p className="text-lg mt-2">You come across a heart-touching story written by a young author. You record it in your unique voice, and soon, listeners are connecting with both the story and your narration. And with every listen, you earn too.</p>
          </div>
        </div>
      </div>

      <div className="text-center mt-12">
        <div className="inline-block bg-gray-900 text-white p-8 rounded-lg shadow-xl mx-auto">
          <h3 className="text-3xl font-semibold">It’s Time to Take the Leap</h3>
          <p className="mt-4 text-lg max-w-xl mx-auto">
            This is your world, and we are merely the stage. If you're a writer, voiceover artist, poet, or creator looking to share your art and grow your audience, come to PageFM. Let us help you not just be heard, but also rewarded.
          </p>
          <Link to ="/profile">
          <button className="mt-6 px-8 py-3 border border-yellow-500 text-yellow-500 font-semibold rounded-md text-lg hover:bg-yellow-600 hover:text-white transition duration-200">
            Join PageFM
          </button>
          </Link>
        </div>
      </div>
    </div>
    </div>
  );
};

export default Creators;
